---
# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

set:
  - pipefail

includes:
  talos: ".taskfiles/talos/Taskfile.yaml"
  helm: ".taskfiles/helm/Taskfile.yaml"
  postgres: ".taskfiles/postgres/Taskfile.yaml"

vars:
  TALOSCONFIG: "{{.ROOT_DIR}}/kubernetes/talos/clusterconfig/talosconfig"
  K8S_DIR: "{{.ROOT_DIR}}/kubernetes"

tasks:
  default:
    silent: true
    cmd: task --list
